name: Build Docker Image

on:
 push:
  paths:
    - "Dockerfile"
    - ".github/workflows/docker.yml"
 schedule:
    # Once monthly at a randomly selected time.
    - cron: "24 3 18 * *"
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: Create Image and Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: icnteam/internet-drafts:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        registry: registry.hub.docker.com
        dockerfile: Dockerfile